# Generated by Django 4.2.29 on 2026-04-13 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoteeregistration',
            name='preacher_name',
        ),
        migrations.AddField(
            model_name='devoteeregistration',
            name='connected_since_unit',
            field=models.CharField(choices=[('MONTHS', 'Months'), ('YEARS', 'Years')], default='MONTHS', max_length=10),
        ),
        migrations.AddField(
            model_name='devoteeregistration',
            name='connected_since_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='devoteeregistration',
            name='japa_rounds',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (24, '24'), (32, '32'), (64, '64')], default=0),
        ),
        migrations.AddField(
            model_name='devoteeregistration',
            name='preacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congregation_devotees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devoteeregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devoteeregistration',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='SevaAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seva_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seva_allocations', to='core.devoteeregistration')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.sevaevent')),
            ],
            options={
                'ordering': ['-allocated_at'],
                'unique_together': {('event', 'devotee')},
            },
        ),
    ]
