# Generated by Django 4.2.29 on 2026-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_devoteeregistration_preacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoteeregistration',
            name='initiated',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='devoteeregistration',
            name='preacher',
            field=models.CharField(blank=True, choices=[('Gopavrinda Pala dasa', 'Gopavrinda Pala dasa'), ('Gaura Gopala dasa', 'Gaura Gopala dasa'), ('Sumadhura Krishna dasa', 'Sumadhura Krishna dasa'), ('Bharata Shreshtha dasa', 'Bharata Shreshtha dasa'), ('Gaura Shyama dasa', 'Gaura Shyama dasa'), ('Abhaya Prahlada dasa', 'Abhaya Prahlada dasa'), ('Nimai Priya dasa', 'Nimai Priya dasa'), ('Lokanath Govinda dasa', 'Lokanath Govinda dasa'), ('Mayapur Shashi dasa', 'Mayapur Shashi dasa'), ('Sakaleshwar Rama dasa', 'Sakaleshwar Rama dasa'), ('Parmananda Chaitanya dasa', 'Parmananda Chaitanya dasa')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sevaevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sevaevent',
            name='seva_location',
            field=models.CharField(blank=True, choices=[('TEMPLE', 'Temple Seva'), ('OUTSIDE', 'Outside Seva'), ('HOME', 'Home Seva')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sevaevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sevaevent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
