# Generated by Django 4.2.29 on 2026-04-14 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_connected_since(apps, schema_editor):
    DevoteeRegistration = apps.get_model('core', 'DevoteeRegistration')
    for devotee in DevoteeRegistration.objects.all():
        value = getattr(devotee, 'connected_since_value', None) or 1
        unit = getattr(devotee, 'connected_since_unit', 'MONTHS')
        if unit == 'YEARS':
            label = 'year' if value == 1 else 'years'
        else:
            label = 'month' if value == 1 else 'months'
        devotee.connected_since = f'{value} {label}'
        devotee.save(update_fields=['connected_since'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_devoteeregistration_initiated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoteeregistration',
            name='connected_since',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.RunPython(copy_connected_since, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='devoteeregistration',
            name='connected_since_unit',
        ),
        migrations.RemoveField(
            model_name='devoteeregistration',
            name='connected_since_value',
        ),
        migrations.CreateModel(
            name='SpecialSevaDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_seva_dates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SpecialSevaSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_seva_signups', to='core.devoteeregistration')),
                ('special_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='core.specialsevadate')),
            ],
            options={
                'ordering': ['special_date__date', 'devotee__name'],
                'unique_together': {('special_date', 'devotee')},
            },
        ),
    ]
