# Generated by Django 4.2.29 on 2026-04-16 05:32

from django.db import migrations, models


def copy_regular_seva_day(apps, schema_editor):
    SevaEvent = apps.get_model('core', 'SevaEvent')
    for event in SevaEvent.objects.all():
        event.day_of_week = event.date.weekday() if event.date else 0
        event.save(update_fields=['day_of_week'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_special_seva_dates_and_connected_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevaevent',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.RunPython(copy_regular_seva_day, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='devoteeregistration',
            name='preacher',
            field=models.CharField(blank=True, choices=[('Gopavrinda Pala dasa', 'Gopavrinda Pala dasa'), ('Gaura Gopala dasa', 'Gaura Gopala dasa'), ('Sumadhura Krishna dasa', 'Sumadhura Krishna dasa'), ('Bharata Shreshtha dasa', 'Bharata Shreshtha dasa'), ('Taruna Krishna dasa', 'Taruna Krishna dasa'), ('Gaura Shyama dasa', 'Gaura Shyama dasa'), ('Abhaya Prahlada dasa', 'Abhaya Prahlada dasa'), ('Nimai Priya dasa', 'Nimai Priya dasa'), ('Lokanath Govinda dasa', 'Lokanath Govinda dasa'), ('Mayapur Shashi dasa', 'Mayapur Shashi dasa'), ('Rajendra Vigraha dasa', 'Rajendra Vigraha dasa'), ('Sakaleshwar Rama dasa', 'Sakaleshwar Rama dasa'), ('Parmananda Chaitanya dasa', 'Parmananda Chaitanya dasa')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sevaevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sevaevent',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
