# Generated by Django 4.2.29 on 2026-04-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weekly_regular_seva_and_cleanup_actions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sevaevent',
            options={'ordering': ['day_of_week', 'start_time', 'title']},
        ),
    ]
