# Generated by Django 4.2.29 on 2026-04-16 05:49

from django.db import migrations, models


def copy_seva_locations(apps, schema_editor):
    DevoteeRegistration = apps.get_model('core', 'DevoteeRegistration')
    for devotee in DevoteeRegistration.objects.all():
        value = getattr(devotee, 'seva_location', '')
        devotee.seva_location_multi = [value] if value else []
        devotee.save(update_fields=['seva_location_multi'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sevaevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoteeregistration',
            name='seva_location_multi',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_seva_locations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='devoteeregistration',
            name='seva_location',
        ),
        migrations.RenameField(
            model_name='devoteeregistration',
            old_name='seva_location_multi',
            new_name='seva_location',
        ),
    ]
